### ISSUE TITLE
Hakim: working with code, Week 1

### ISSUE THREAD

**Issue by Hkm9** [HackYourFutureBelgium/class-7#12]
- [x] (computer) Software Installations
  - [x] [Chromium](https://download-chromium.appspot.com/), [Firefox](https://www.mozilla.org/en-US/firefox/developer/) or [Brave](https://brave.com/download/): All great browsers with ES6, HTML5 & CSS3 support plus pre-installed, top-knotch developer tools.  Try each one to see what you like best!
  - [x] [Visual Studio Code](https://code.visualstudio.com/download): Like Microsoft Word, but for code ...  and _sooooo_ much better.  After installing VSC, be sure to install these plug-ins:
    - [x] [Markdown Preview Github Styling Custom](https://marketplace.visualstudio.com/items?itemName=dmodalek.markdown-preview-github-styles-custom)
    - [x] [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)
    - [x] [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode#overview)
  - [x] [GitKraken](https://www.gitkraken.com/download): A program that will help you master using git.
  - [x] (If you have windows) [Git For Windows](https://gitforwindows.org/): This will allow you to use the same terminal commands & tools as Linux or Mac computers.
- [x] (computer) Start an HYF Directory
- [x] [My bio on the class repo](https://github.com/hackyourfuturebelgium/class-7/blob/master/student-bios/Hkm9.md)
- [x] [Hack My Future](https://github.com/Hkm9/hack-my-future)
- [x] [Markdown Home Page](https://Hkm9.github.io) - my multi-page markdown home portfolio, live on github pages

**Comment by Hkm9** [comment]
I have forked and cloned the repo ( Hkm9.github.io ) using GitKraken then edited the readme file from the folder using VSC. Then I tried to push/pull (am not sure the terminology to use here) the edited txt to the web main repo to pull it from there and merge it to the main repo. Thanks for your help ......

**Comment by colevandersWands** [comment]
It sounds like you might be blending the two assignments.  

* One is to do a PR with your bio to the class repo. This you can do completely on GitHub without cloning.  To complete this assignment you add your bio in a new file on _your_ fork of `class-7`, then send a Pull Request from your account to ours. (All on GitHub)
* The second is to create the site `Hkm9.github.io`.  For this project you need to clone, edit in VSC, and push your changes to GitHub.  There is no pull requesting necessary.

The big difference between the two assignments is that in the first, you are practicing collaborating on one shared code-base (this repository). While in the second you are practicing working individually, synchronizing the code between your computer and GitHub.

You won't be able to send a PR from Hkm9.github.io to the class repository because Hkm9.github.io is not a _fork_ of this repo.

**Comment by colevandersWands** [comment]
Looking more closely at your student-bio in this repository, I see that you have written it directly in this repository.  Instead of using a fork & PR.

I've removed your bio from this repository so you can go through the process of adding it by PR.  (but i've saved your markdown [right here](https://gist.github.com/colevandersWands/6752f134b01641ba006021b41dc6c48c) so you don't have to re-write it)

**Comment by Hkm9** [comment]
Thanks and I have done the 1st one and it was a success but for the second one, I created a repo named Hkm9.github.io then clone this by using GitKraken then edit Readme.md by using VSC then I tried to push the change from GitKraken to Github but Its not happening at the moment. Thanks for your time

**Comment by Hkm9** [comment]
Thanks and I have done the 1st one and it was a success but for the second one, I created a repo named Hkm9.github.io then clone this by using GitKraken then edit Readme.md by using VSC then I tried to push the change from GitKraken to Github but Its not happening at the moment. Thanks for your time

**Comment by colevandersWands** [comment]
Can you share a screen shot of your GitKraken @Hkm9 ?

**Comment by Hkm9** [comment]
![Screenshot 2020-01-09 at 11 52 16](https://user-images.githubusercontent.com/55857486/72061615-8ab92100-32d6-11ea-8120-9a0229d0948c.png)

**Comment by NickMarinade** [comment]
![72061615-8ab92100-32d6-11ea-8120-9a0229d0948c](https://user-images.githubusercontent.com/59340748/72072636-aaf4da00-32ee-11ea-83c2-a9589e1ea006.png)

Seems like u didnt commit it yeat, u should go to //WIP, commit, and then push it
