### ISSUE TITLE
Rahel Semu: Week 1, State

### ISSUE THREAD

**Issue by Rahela-HYF** [HackYourFutureBelgium/class-7#149]
### Prep Work

- [x] What is State?
     - [x] Stack Overflow
Objects & Arrays
- [x] Reference vs. Value (Mosh video)
- [x] Reference vs. Value (CodeBurst article)
DOM Manipulation
- [x] DOM Tree (js.info)
- [x] Walking the DOM (js.info)
- [x] getElement & querySelector (js.info)

### Biggest & Smallest Project: 

- [repo](https://github.com/Rahela-HYF/biggest-and-smallest)
- [live](https://rahela-hyf.github.io/biggest-and-smallest/)
- [x]  [handler](https://github.com/Rahela-HYF/biggest-and-smallest/tree/biggest-and-smallest)
- [x]  [listeners]()
### up-down-code-along project
- [repo](https://github.com/Rahela-HYF/up-down-code-along)

### Exercises:
Isolating JavaScript
- [ ] Continue the FreeCodeCamp JavaScript exercises
- [ ] Sign into FreeCodeCamp using your GitHub Account
- [ ] Complete Basic Data Structures
- [ ] Begin Basic Algorithm Scripting

### Fork JS Exercises
>- [x]  week-3 [repo](https://github.com/Rahela-HYF/js-exercises/commit/43c7e8b2cf0b64a23a8c5b63f0687c79913988d8)
>- [x]  week-3-practice [repo](https://github.com/Rahela-HYF/js-exercises/tree/master/week-3-practise)

### Integrating JavaScript

 - [x]  Fork dom-manipulation [repo](https://github.com/Rahela-HYF/dom-manipulation) 
### Challenge Exercises

- [x] (Isolate) Fork js-exercises-tdd
- [x] (Isolate) Fork javascript-exercises
- [x] (Integrate) Fork javascript-you__dom-exercises
- [x] (Integrate) Fork practice-and-learn-the-dom
- [x] (Integrate) Fork using-user-input

**Comment by dfdeagle47** [comment]
It seems my comment didn't pass through, let me start again.

# Biggest & Smallest Project

The button work when clicking on them, but there's an issue with how the biggest and smallest numbers are computed.

- The variable `numbers.biggest` should correspond to the biggest number that the user has saved.
- The variable `numbers.smallest` should correspond to the biggest number that the user has saved.

Currently, it only saves the `numbers.biggest` when the current number is >= 0 and only saves `numbers.smallest` when the current number is < 0. The issue comes from [those lines](https://github.com/Rahela-HYF/biggest-and-smallest/blob/master/handlers/save-number.js#L11-L25): the conditions compare the numbers to "0". Instead, you should compare the `current` number to the previous value of `numbers.biggest` and `numbers.smallest`. You should adjust the conditions to reflect this.

The reset doesn't work for the `biggest` and `smallest` elements in the HTML. [Your code](https://github.com/Rahela-HYF/biggest-and-smallest/blob/master/handlers/reset.js#L13-L14) is almost good: you're using

```js
document.getElementById('biggest').value = numbers.biggest;
document.getElementById('smallest').value = numbers.smallest;
```

However those elements display their values using `.innerHTML` (instead of `.value` for inputs), so it should be

```js
document.getElementById('biggest').innerHTML = numbers.biggest;
document.getElementById('smallest').innerHTML = numbers.smallest;
```

# up-down-code-along project

The logic for the up button looks good. You should be able to apply the logic for the down button because it's very similar except you decrement the number.
The reset logic should also look similar except you reset the state to the initial values defined in [data/number.js](https://github.com/Rahela-HYF/up-down-code-along/blob/master/data/numbers.js).

# JS exercises

- ✅ https://github.com/Rahela-HYF/js-exercises/blob/master/week-3-practise/level-1/1-find.js
- ❌ https://github.com/Rahela-HYF/js-exercises/blob/master/week-3-practise/level-1/2-every.js: it doesn't work as expected because the bush is considered "safe" if it **only** contains pink berries. However, your condition is the opposite `color !== "Pink"` whereas it should be `color === "pink"` (there was also a typo in "Pink" instead of "pink").
- ✅ https://github.com/Rahela-HYF/js-exercises/blob/master/week-3-practise/level-1/3-filter.js
- ✅ https://github.com/Rahela-HYF/js-exercises/blob/master/week-3-practise/level-2/1-map.js
- ❌ https://github.com/Rahela-HYF/js-exercises/blob/master/week-3-practise/level-2/2-map.js: it does not work as expected because the signature of the map function is actually
  ```js
  function eligibleList(element) {
    // Do something with `element`
    // On the first loop, element = ["Ahmed", 8], so element[0] = "Ahmed" and element[1] = 8
    // On the second loop, element = ["Clement", 10], so element[0] = "Clement" and element[1] = 10
    // ...
  }
  ```
  So the logic should be a bit different.
- ✅ https://github.com/Rahela-HYF/js-exercises/blob/master/week-3-practise/level-2/3-filter.js
- ✅ https://github.com/Rahela-HYF/js-exercises/blob/master/week-3-practise/level-3/1-practise-all.js

- ✅ https://github.com/Rahela-HYF/js-exercises/blob/master/week-3/A-array-find/exercise.js. You could also replace `name[0] == "A"` by `name.startsWith("A")`.
- https://github.com/Rahela-HYF/js-exercises/blob/master/week-3/B-array-some/exercise.js. You should be able to use
  ```js
  process.exit(1);
  ```
  instead of
  ```js
  process.on('exit', function() {
    console.log('process terminate');
    process.exit(1);
  });
  ```
- https://github.com/Rahela-HYF/js-exercises/tree/master/week-3/C-array-every. You're perhaps having trouble on this exercise because of the signature of the function which is
  ```js
  function containonlyStudent(name) {
    // Do something with `name`
    // On the first loop, name = "Omar"
    // On the second loop, name = "Austine"
    // ...
  }
  ```
  and you should use the [`students.includes(...)`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) method takes an element as the parameter and returns true if the element is contained in the array. So for instance `students.includes("Omar")` returns `true` because `"Omar"` is part of the `students` array.
- ❌ https://github.com/Rahela-HYF/js-exercises/blob/master/week-3/D-array-filter/exercise.js. This won't work as intended. Again, it might be because the signature of the function is not what you're expecting
  ```js
  function isNum(element) {
    // Do something with `element`
    // On the first loop, element = [0, 3]
    // On the second loop, element = [1, 2]
    // ...
  }
  ```
  You could use [`Array.isArray(...)`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray) to check if the element is an array and check if the elements in that sub-array are numbers using [`typeof ... === 'number'`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof).
- ✅ https://github.com/Rahela-HYF/js-exercises/blob/master/week-3/E-array-map/exercise.js. You can also try the alternative syntax using [arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions).
- ✅ https://github.com/Rahela-HYF/js-exercises/blob/master/week-3/F-array-forEach/exercise.js. Good job. You can also simplify it like this
  ```js
  arr.forEach(function(num) {
    console.log(mulofthreeandfive(num));
  });
  ```
