### ISSUE TITLE
Feridun Akyol: Week 2, State

### ISSUE THREAD

**Issue by feridunAKYOL** [HackYourFutureBelgium/class-7#153]
### Prep Work

- [x] Traversy DOM Crash Course 
- [ ] JS Dom Tutorials: Accessing The DOM
- [ ] DOM Tree (js.info)
- [ ] Walking the DOM (js.info)
- [ ] getElement & querySelector (js.info)

### Project: `numbery-and-nany`

- [repository](https://github.com/feridunAKYOL/numbery-and-nany)
- [live demo](https://feridunakyol.github.io/numbery-and-nany/)
- [x]  [step 1](link to branch for version 1)
- [x]  [step 2](link to branch for version 2)
- [x]  [step 3](link to branch for version 3)
- [x]  ...

#### Isolating JavaScript
- [x]  js-exercises-tdd - `I.pass-tests`: [repo](https://github.com/feridunAKYOL/js-exercises-tdd)
- [ ]  early-return: [repo](https://github.com/user-name/repo-name), [live (if there is)]()
>> - [ ] 1-isolate
>> - [ ] **2-integrate**  [repo](https://github.com/user-name/repo-name), [live]()

##### JS DOM Tutorials:
- [x] Tutorial 1: Accessing the DOM
- [x] Tutorial 2: Manipulating the DOM

### Challenge Exercises
- [ ] (Isolate) Continue Basic Algorithm Scripting
- [ ] (Isolate) Fork javascript-exercises
- [ ] (Integrate) Fork javascript-you__dom-exercises
- [ ] (Integrate) Fork practice-and-learn-the-dom
- [ ] (Integrate) Fork using-user-input

> [Follow this link](https://github.com/HackYourFutureBelgium/class-6/issues/59) to study a well-done homework issue.

**Comment by feridunAKYOL** [comment]
I can do only the save and sort part :cry:

**Comment by dfdeagle47** [comment]
# Project: `numbery-and-nany`

Good job so far, here are some remarks to improve the project:

[`saveHandler`](https://github.com/feridunAKYOL/numbery-and-nany/blob/master/handler.js)

- You target the containers with id `number` and `str` and add the `li` elements as children. However, those containers are actually the `div` wrappers. Instead, you should target the `ul` (ul = unordered list) elements with ids `ulNumber` and `ulStr`.
- The state should also be updated with the values entered by the user. The state is represented by

  ```js
  const entries = {
    numbery: [],
    nany: [],
  };
  ```

  where `numbery` is an array with all the numeric entries and `nany` is an array with all the non-numeric entries.

- One part of the spec is

  > If a user inputs the same value twice, you should not save it in your app. Your lists should never have repeated values

  This means that before adding a value to the DOM, you should check if it hasn't been added yet. This is linked to the previous point: if you store all the values in the state, you'll be able to tell if that value has already been added.

[`resetHandler`](https://github.com/feridunAKYOL/numbery-and-nany/blob/master/reset.js)

Currently, it doesn't work but here are some pointers

- You target `ulNumber`. That's fine (you'll also have to target `ulStr`), but it doesn't work at the moment since the `li` elements are added to the containers `numbers` and `str` (see point above). Once the previous point has been fixed, this will be better. One way you could clear the `ul` would be to use `innerHTML` and set it to an empty string.
- Note this handler should also update the app state `entries`.

- minor: add a min-width on the input
- reset doesn't work (it should reset both uls to their default values)
- remove not implemented
- Save looks good
- Save should not add the value if it already exists

# Exercises

- ✅ 01-add-one: looks good. You could also use the function `.map()` to perform this transformation.
- ✅ 02-get-word-lengths: good. Same as above, you can also use `.map()` to solve it.
- ✅ 03-sum-numbers: good job on the `.reduce()`. It's also useful to add the default value as the second parameter to the function, otherwise it will fail when running the function with an empty array `addNumbers([])`. The initial value of the sum should be 0 here so you would write:
  ```js
  function addNumbers(numbers) {
    const sum = numbers.reduce((total, item) => total + item, 0);
    return sum;
  }
  ```
- ✅ 04-find-needle.
- ✅ 05-factorial.
- ✅ 06-remove-middle
- ✅ 07-second-largest. You can also use an arrow function for the sort function

  ```js
  const arr = numbers.sort((a, b) => a - b);
  ```

- ✅ 08-get-average. Since you're already filtering using `typeof arr[i] === 'number'`, you don't need to cast to a number, you can directly use `sum = sum + arr[i];`. An alternative way of doing this exercise is using `.filter()` to remove non-numeric values and `.reduce()` to calculate the sum (see exercise 03-sum-numbers) and divide by the length of the array to get the average value.
- ✅ 09-car-sales. `car.price` is already a number, so you don't need to cast to a number using `Number(...)`. When you have a bunch of `if`'s where you compare the same variable, you can also use a [`switch` statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch) instead.
- ❎ 10-paint-ford: the transformation is correct ("Pink"), however the tests don't pass. This is because you shouldn't modify the initial array. Remember that arrays are passed by reference, so if you modify an element of the array in the output, it will also modify the element of the initial array. To work around this, you could copy the array (using the `JSON.parse(JSON.stringify(array))` method) or instead return a new array from the initial array using `.map()`.
- 11-cities-formatter. Here the `format` function takes a second parameter called `transform` which is the function you should use to transform the initial array. You could use `.map()` with this function to create the output array.

**Comment by feridunAKYOL** [comment]
@dfdeagle47 thank you very much :pray: 
you spent a lot of time
