### ISSUE TITLE
RahelSemu: Week 2, State

### ISSUE THREAD

**Issue by Rahela-HYF** [HackYourFutureBelgium/class-7#155]
### Prep Work

- [x] Traversy DOM Crash Course 
- [x] JS Dom Tutorials: Accessing The DOM
- [x] DOM Tree (js.info)
- [x] Walking the DOM (js.info)
- [x] getElement & querySelector (js.info)

### Project: numbery-and-nany

- [repo](https://github.com/Rahela-HYF/numbery-and-nany/tree/master)
- [live](https://rahela-hyf.github.io/numbery-and-nany/)
- [x]  [step 1] index
- [x]  [step 2] CSS
- [x]  [step 3 Adding Listeners](https://github.com/Rahela-HYF/numbery-and-nany/tree/Listener1)
- [x]  [step 4 adding handlers](https://github.com/Rahela-HYF/numbery-and-nany/tree/Handler)

#### Isolating JavaScript 
 - [ ] Fork js-exercises-tdd  complete the exercises in I.pass-tests
     [repo](), [live]()
- [ ] Fork early-return:
>> - [ ] complete the 1-isolate [repo](), [live]()
>> - [ ] complete the 2-integrate**  [repo](), [live]()

##### JS DOM Tutorials:
- [x] Tutorial 1: Accessing the DOM
- [x] Tutorial 2: Manipulating the DOM

### Challenge Exercises
- [ ] (Isolate) Continue Basic Algorithm Scripting
- [ ] (Isolate) Fork javascript-exercises
- [ ] (Integrate) Fork javascript-you__dom-exercises
- [ ] (Integrate) Fork practice-and-learn-the-dom
- [ ] (Integrate) Fork using-user-input

**Comment by dfdeagle47** [comment]
# Project: numbery-and-nany

Nice work on the project. Good structure (files are clearly named and separated). Here are a few areas to improve the existing implementation

- (minor) For the HTML, you correctly use `li` elements for the values. You should also use a `ul` (= unordered list) element to wrap the `li` elements: you should transform the `<code>` element to a `<ul>` element instead.

`saveHandler`

- You correctly check if the numbers are already present, so they won't get added twice. Currently, you use `indexOf`, but you could also use [`.includes()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) which might be easier to read in this case. The statement `array.includes(value)` directly returns `true` or `false`, instead of returning an index.
- The statement `nanyElement.appendChild(newEntry);` should already append your child element in the DOM, so you should be able to remove `document.getElementById('nany').appendChild(nanyElement).innerHTML = entries.nany;` normally. Also, side-note: it shouldn't be added to modify the `innerHTML` (as in `document.getElementById('nany').appendChild(nanyElement).innerHTML = entries.nany;`) because the `appendChild` statement should already add the element to the DOM.
- I see that you correctly update the app state (`entries`) 👍.
- Great that you also added the logging part.

`removeHandler`

- You have the correct idea by checking if the element exists in the app state (`entries.nany.indexOf(elem);`). You should also check this for the other array `entries.numbery`.
- The reason why it doesn't work completely as intended (the design breaks) is because you're overwriting the `innerHTML` with the values in the state, but without the HTML structure (the `li` elements). Instead, you should map the arrays to their corresponding HTML representation by creating the `li` elements, and use those to update the `innerHTML`. An alternative would be to find the corresponding element `li` in the DOM and use [`.removeChild()`](https://developer.mozilla.org/en-US/docs/Web/API/Node/removeChild) on the `ul` parent.

`resetHandler`

- It works 👍. You could also reset the containers to an empty string (right now you're resetting to an empty array) to make it cleaner
  ```js
  document.getElementById('number').innerHTML = '';
  ```

A little bit more work and I think you should be able to fix the `removeHandler`.

**Comment by dfdeagle47** [comment]
Closing old issue.
