### ISSUE TITLE
FeridunAkyol: Week 3, State

### ISSUE THREAD

**Issue by feridunAKYOL** [HackYourFutureBelgium/class-7#166]
### Prep Work

- [x] Traversy DOM Crash Course 
- [x] JS Dom Tutorials: Accessing The DOM
- [x] DOM Tree (js.info)
- [x] Walking the DOM (js.info)
- [x] getElement & querySelector (js.info)

### Project: `Even or Odd`

- [repository](https://github.com/feridunAKYOL/even-or-odd)
- [live demo]( https://feridunakyol.github.io/even-or-odd/)
- [x]  [HTML/CSS](https://github.com/feridunAKYOL/even-or-odd/pull/1/files)
- [x]  [Listeners](https://github.com/feridunAKYOL/even-or-odd/pull/2/files)
- [x]  [Handlers](https://github.com/feridunAKYOL/even-or-odd/pull/3/files)
- [x]  [Render List](https://github.com/feridunAKYOL/even-or-odd/pull/4/files)

#### Isolating JavaScript
- [x]  js-exercises-tdd - `II.write-tests`: [repo](https://github.com/feridunAKYOL/js-exercises-tdd)

#### Integrating JavaScript
- [x] dom-components [REPO](https://github.com/feridunAKYOL/dom-components/tree/master/exercises) -- [LIVE](https://feridunakyol.github.io/dom-components/)

### Challenge Exercises
- [x] (Isolate) Continue Basic Algorithm Scripting 
![](https://raw.githubusercontent.com/feridunAKYOL/feridunakyol.github.io/master/basic%20Algorithm%20Scripting.png)
- [x] (Isolate) Fork javascript-exercises
- [ ] (Integrate)Keep learning about TDD: what is TDD?, online TDD exercises (no NPM troubles :)
- [x] (Integrate)  Fork javascript-you__dom-exercises [REPO](https://github.com/feridunAKYOL/javascript-toy__dom-exercises)
- [ ] (Integrate) Fork practice-and-learn-the-dom
- [ ] (Integrate) Fork using-user-input

> [Follow this link](https://github.com/HackYourFutureBelgium/class-6/issues/59) to study a well-done homework issue.

**Comment by dfdeagle47** [comment]
# Even or Odd

Good work so far. Great idea to prevent adding the same number multiple times using an early return.

Here are some advices to improve the project:

- The code to render the list is very similar in the different handlers. Instead, you could extract the logic to another function (see `renderList`) which takes two parameters:
  - `currentArray`: the array of numbers you want to display
  - `currentDisplayed`: the value of the `displayed` variable
  This function could return a DOM element like
  ```html
  <div>
    <h4>evens</h4>
    <ul>
      <li>2</li>
      <li>6</li>
      <li>10</li>
    </ul>
  </div>
  ```
  which you could render in the DOM in the correct place (via `.innerHTML`).
  - This function could also be used in `saveHandler` to re-render each time a number has been added.
- You added `onfocus="this.value=''"` in the index.html. I don't think this is actually needed. Instead, you could clear the input in the `saveHandler` (`document.getElementById('input').value = ''`). Otherwise, the input is only cleared when it's focused, not when the number is saved which could be confusing to the user. Also, if I haven't saved the number and I click somewhere else and click back on the input, it will clear it.
- `resetHandler`: there's an error "Uncaught ReferenceError: currentListComponent is not defined". This is because you haven't used `renderList` currently.
  - Also this handler should reset the input as well.
- `saveHandler`: there's an error "Uncaught ReferenceError: newInput is not defined". This because you haven't defined the variable `newInput` which should be new value for the input.
  - You should also update the UI for the input from the state here. This is here that you would clear the input.


# Isolating JavaScript

Tests look good 👍

- ✅ 01-greet-people
- ✅ 02-remove-vowels. (Minor) in js, a string cannot be changed even if it's passed by reference, so you don't actually need to check if it has been changed.
- ✅ 03-remove-vowels-from-array
- ✅ 04-numbers-greater-than-10
- ✅ 05-get-second-third-smallest
- ✅ 06-largest-number
- ✅ 07-get-even-numbers

# Integrating JavaScript

I don't specific comments here, everything looks good 👌.

- ✅ study-links.js
- ✅ linked-thumbnail.js
- ✅ study-links.js. It's a good idea to remember the `Object.keys(...)` function, it's pretty useful.
- ✅ thumbnail.js

**Comment by feridunAKYOL** [comment]
@dfdeagle47 thank you for your feedback :pray: 
and thank you for your time and effort in class...
